### ISSUE TITLE
修改一下关于表单的操作

### ISSUE THREAD

**Issue by William-YanHua** [FlyingRat1024/appManagementServer#2]
比如上传一张入库单，它可能有很多材料一起上传

**Comment by William-YanHua** [comment]
是否还需要考虑一下这个材料不存在于数据库的情况怎么办？

**Comment by FlyingRat1024** [comment]
> 是否还需要考虑一下这个材料不存在于数据库的情况怎么办？

逻辑上来说是不用的，因为我们的材料都是选择上去填写的，相关操作我后续写把
