### ISSUE TITLE
获取表单列表的接口统一化

### ISSUE THREAD

**Issue by William-YanHua** [FlyingRat1024/appManagementServer#5]
返回字段只要四个{table_id, table_name, creator, create_time} 或者三个都行{table_id, creator, create_time}.但是要么统一为四个，要么统一为三个，然后键的名字就按照这上面的来，我这样前端好做一点

**Comment by William-YanHua** [comment]
另外，接口的形式也统一下，我会传给你一个{userID : id}。路由就按原来的就行

**Comment by FlyingRat1024** [comment]
> 另外，接口的形式也统一下，我会传给你一个{userID : id}。路由就按原来的就

> 返回字段只要四个{table_id, table_name, creator, create_time} 或者三个都行{table_id, creator, create_time}.但是要么统一为四个，要么统一为三个，然后键的名字就按照这上面的来，我这样前端好做一点

这个我可能会给你返回多了，你直接不用就好了  : )
